# Generated by Django 4.2 on 2023-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0011_alter_vehiculo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
