# Generated by Django 4.2 on 2023-05-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0012_alter_vehiculo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, verbose_name='Placa'),
        ),
    ]
