# Generated by Django 4.2 on 2023-05-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductoresApp', '0008_alter_conductor_options'),
        ('vehiculosApp', '0013_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='conductoresApp.conductor'),
        ),
    ]
