# Generated by Django 4.2 on 2023-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0014_alter_vehiculo_options_alter_vehiculo_conductor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=20, verbose_name='Modelo'),
        ),
    ]
