# Generated by Django 4.2 on 2023-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0015_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=21, verbose_name='Modelo'),
        ),
    ]
