# Generated by Django 4.2 on 2023-05-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
