# Generated by Django 4.2 on 2023-05-10 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0002_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('Mercancia', 'Mercancia'), ('Pasajero', 'Pasajero')], default='Mercancia', max_length=20, verbose_name='Tipo'),
        ),
    ]
