# Generated by Django 4.2 on 2023-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductoresApp', '0005_rename_identicacion_conductor_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido'),
        ),
    ]
