# Generated by Django 4.2 on 2023-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductoresApp', '0006_alter_conductor_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='direccion',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Direccion'),
        ),
    ]
