# Generated by Django 4.2 on 2023-05-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductoresApp', '0007_alter_conductor_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
    ]
